<?php

/**
 * @file bangpoundefq.module
 *
 * Provides EFQ as panels content, configurable by the administrator.
 * Each EFQ provided as panel content must be configured in advance,
 * but once configured, building panels with EFQ is a little bit simpler.
 */

/**
 * Implementation of hook_ctools_plugin_dierctory() to let the system know
 * where our content_type plugins are.
 */
function bangpoundefq_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function bangpoundefq_ctools_plugin_api($module, $api) {
  if ($module == 'entitylist' && $api == 'entitylist_lists') {
    return array('version' => 1);
  }
}
