<?php

/**
 * @file entityfieldquery_content.module
 *
 * Provides views as panels content, configurable by the administrator.
 * Each view provided as panel content must be configured in advance,
 * but once configured, building panels with views is a little bit simpler.
 */

/**
 * Implementation of hook_ctools_plugin_dierctory() to let the system know
 * where our content_type plugins are.
 */
function entityfieldquery_content_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools') {
    return 'plugins/' . $plugin_type;
  }
  if ($owner == 'entityfieldquery_content') {
    return 'plugins/'. $plugin_type;
  }
}

/**
 * Implements hook_ctools_plugin_type().
 */
function entityfieldquery_content_ctools_plugin_type() {
  $plugins['queries'] = array();
  return $plugins;
}
